# Generated by Django 4.2.3 on 2023-12-14 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_customuser_options_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
