# Generated by Django 4.2.3 on 2023-07-17 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
