# Generated by Django 4.2.3 on 2023-12-14 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communication", "0005_alter_conversation_members_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="members",
            field=models.ManyToManyField(
                related_name="conversations_as_member", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="conversationmessage",
            name="sender",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
